export type JobItemType = {
  conm: string
  regymd: string
  ddlnymd: string
  sj: string
  qlfcrqrmnt: string
  eplymtform: string
  rcrtmtnoppl: string
  wagecdn: string
  addr: string
  dutycn: string
}

export const dummyData = [
  {
    no: 423,
    conm: '(주)경안테크',
    sj: 'MS-SQL 데이터스키마 경력및 신입 모집합니다.',
    qlfcrqrmnt: '관계없음',
    regymd: '2022-01-04',
    ddlnymd: '2022-01-28',
    dutycn:
      '*전산역량 및 컴퓨터공학과 우대 MS-SQL 데이터모델링 기반 대시보드 구축및 입출력폼 개발업무 경력우선이나 기초역량있을시 외부교육통한 직무역량개발 및 프로젝트 수행가능',
    rcptddlnday: '2022.01.28',
    eplymtform:
      '기간의 정함이 있는 근로계약3 개월/ 계약기간 만료 후 상용직전환검토/ 파견근로 비희망/ 대체인력채용 비희망',
    rcrtmtnoppl: '1명',
    wagecdn: '월급2;000;000원 이상 ~ 2;500;000원 이하; 면접 후 재조정 가능',
    crrcdn: '관계없음',
    acbg: '학력무관',
    forlangablty: '',
    major: '',
    qlfclcn: 'SQLD(SQL개발자);SQLP(SQL전문가)',
    hpmltrysvrcexptnrqrmnt: '비희망',
    prfrnlcdn: '',
    etcpfrncs: '',
    slctnmthd: '서류;면접',
    rcptmthd: '워크넷;기타(*근무시간 및 급여 등 상세 근로조건은 입사 전 재확인하시기 바랍니다.)',
    sbmsndocsformatch: '',
    sbmsndocsprmtrl: '자기소개서;졸업증명서;경력증명서',
    plcwork: '(16977)  경기도 용인시 기흥구 강남로 9; 태평양프라자 501호',
    ogdpinduscmplx: '',
    nrbysbwystn: '에버라인 강남대 2번출구 500M',
    workhrform: '평일 : (오전) 8시 30분~(오후) 6시 00분; 주 5일 근무; 평균근무시간 : 40',
    pnsn4majinsrn: '국민연금 고용보험 산재보험 의료보험',
    svpaygivemthd: '퇴직금',
    etcwlfrbnft: '',
    dsabldcnvntfclts: '',
    deptnm: '',
    telno: '07040707693',
    fxno: '',
    addr: '16977 경기도 용인시 기흥구 강남로 9; 태평양프라자 501호',
  },
  {
    no: 482,
    conm: '엠즈푸드시스템㈜',
    sj: '[엠즈푸드시스템(주)] 물류센터 운영관리직(경력;...',
    qlfcrqrmnt: '관계없음',
    regymd: '2022-01-03',
    ddlnymd: '2022-01-31',
    dutycn:
      '1. 회사소개  - 매일홀딩스 계열사  - 프랜차이즈 식자재 유통물류회사(카페; 베이커리; QSR)  - 2013년 설립 2. 담당업무  - 물류센터 운영관리  - 차량; 운송관리  - 사무관리(물류CS; 주문관리) 3. 근무지  - 엠즈푸드시스템(주) 수도권 물류센터(경기도 용인시 처인구 남사읍 원암로 439) 4. 근무조건  - 복장 : 자율복  - 근무일 : 주5일(토요일 및 주중 공휴일 당직 운영)  - 연봉 : 협의 후 결정  - 식대; 자기개발비 지원  - 각종 경조사 지원  - 기숙사 제공 5. 우대사항  - 물류관련 전공자  - 물류관련 자격증 소지자',
    rcptddlnday: '2022.01.31',
    eplymtform: '기간의 정함이 없는 근로계약/ 파견근로 비희망/ 대체인력채용 비희망',
    rcrtmtnoppl: '1명',
    wagecdn: '연봉30;000;000원 이상 ~ 35;000;000원 이하; 면접 후 재조정 가능',
    crrcdn: '관계없음',
    acbg: '학력무관',
    forlangablty: '',
    major: '산업공학(학과 : 산업공학) 무역·유통학(학과 : 물류학과)',
    qlfclcn: '',
    hpmltrysvrcexptnrqrmnt: '비희망',
    prfrnlcdn: '',
    etcpfrncs: '',
    slctnmthd: '서류;면접',
    rcptmthd: '워크넷;기타(근무시간 및 급여 등 상세 근로조건은 입사 전 재확인하시기 바랍니다.)',
    sbmsndocsformatch: '',
    sbmsndocsprmtrl: '이력서;자기소개서',
    plcwork: '(17123)  경기도 용인시 처인구 남사읍 원암로 439',
    ogdpinduscmplx: '',
    nrbysbwystn: '',
    workhrform: '평일 : (오전) 9시 00분~(오후) 6시 00분; 주 5일 근무; 평균근무시간 : 40',
    pnsn4majinsrn: '국민연금 고용보험 산재보험 의료보험',
    svpaygivemthd: '퇴직금',
    etcwlfrbnft: '기숙사',
    dsabldcnvntfclts: '',
    deptnm: '',
    telno: '07048705636',
    fxno: '',
    addr: '17123 경기도 용인시 처인구 남사읍 원암로 439',
  },
  {
    no: 554,
    conm: '주식회사 엠포스',
    sj: '[용인/조립/정규직/연봉2800이상] 헬스케어 제...',
    qlfcrqrmnt: '신입',
    regymd: '2022-01-03',
    ddlnymd: '2022-01-31',
    dutycn:
      '안녕하세요? SMPS 개발/제조 전문 기업 주식회사 엠포스에서 조립 생산 정규직 직원을 채용하려고 합니다. 먼저 저희 회사의 모집 공고를 봐 주셔서 감사드립니다. 엠포스는 작은 회사이지만 성장하고 있는 회사입니다. (대략적인 매출액 기준 2019년 20억; 2020년 28억; 2021년 43억; 2022년 60억 예상) 회사 발전의 초기단계에 합류한 사람에게는 큰 기회가 있는 법입니다. 지금 바로 입사지원하셔서 좋은 기회를 만들어 보시기 바랍니다.  당사는 용인시 처인구 이동읍 용인테크노밸리(덕성산업단지) 내에 입주해 있으며 2019년 8월에 입주한 신사옥입니다.  넓고 쾌적한 환경에서 근무하실 수 있습니다. 주로 헬스케어제품의 조립업무를 담당하며 완성된 제품의 기능검사 업무도 담당할 예정입니다. 납땜에 능숙하신 분을 선호합니다. 감사합니다. 자격요건ㆍ학력 : 무관ㆍ나이/성별 : 무관 담당업무ㆍ헬스케어제품 조립; 기능검사 지원자격ㆍ경력조건 : 신입 우대사항ㆍ전기/전자공학ㆍ인근거주자; 운전가능자; 해당직무 근무경험 근무조건ㆍ근무형태: 정규직(수습기간: 3개월; 수습기간중 정상급여) ㆍ근무일시: 주 5일(월~목) 오전 9시~오후 6시30분; (금) 오전 9시~오후4시ㆍ급여: 2;800~3;000만원ㆍ근무지역: (17130) 경기 용인시 처인구 이동읍 덕성산단2로 12-1',
    rcptddlnday: '채용시까지',
    eplymtform: '기간의 정함이 없는 근로계약/ 파견근로 비희망/ 대체인력채용 비희망',
    rcrtmtnoppl: '2명',
    wagecdn: '연봉28;000;000원 이상 ~ 30;000;000원 이하;',
    crrcdn: '신입',
    acbg: '학력무관',
    forlangablty: '',
    major: '전자공학(학과 : 전기·전자공학과)',
    qlfclcn: '',
    hpmltrysvrcexptnrqrmnt: '비희망',
    prfrnlcdn: '',
    etcpfrncs: '',
    slctnmthd: '서류;면접;기타(*근무시간 및 급여 등 상세 근로조건은 입사 전 재확인하시기 바랍니다.)',
    rcptmthd: '워크넷',
    sbmsndocsformatch: '',
    sbmsndocsprmtrl: '이력서;자기소개서',
    plcwork: '(17130)  경기도 용인시 처인구 이동읍 덕성산단2로 12-1; 엠포스',
    ogdpinduscmplx: '',
    nrbysbwystn: '',
    workhrform:
      '평일 : 월요일~목요일 (오전) 9시 00분~(오후) 6시 30분금요일 (오전) 9시 00분~(오후) 4시 00분; 주 5일 근무; 평균근무시간 : 40',
    pnsn4majinsrn: '국민연금 고용보험 산재보험 의료보험',
    svpaygivemthd: '퇴직연금',
    etcwlfrbnft: '',
    dsabldcnvntfclts: '',
    deptnm: '',
    telno: '07082376884',
    fxno: '',
    addr: '17130 경기도 용인시 처인구 이동읍 덕성산단2로 12-1; 엠포스',
  },
  {
    no: 788,
    conm: '주식회사 주현개발',
    sj: '건설현장 근로자모집(잡부)',
    qlfcrqrmnt: '경력',
    regymd: '2021-12-29',
    ddlnymd: '2022-01-12',
    dutycn:
      '[철근콘크리트시공 > 자재관리]거푸집 반입·보관하기;철근 반입·보관하기 [철근콘크리트시공 > 시공 전 준비]거푸집 설치 계획하기 [철근콘크리트시공 > 거푸집 설치]먹메김 하기;동바리 설치하기;거푸집 설치·검사하기;거푸집 해체하기 현장 주소: 경기도 용인시 기흥구 마북동 212-2현장 이름: 용인 마북동 동부건설 공동주택 신축 공사 현장(동부건설) (주현개발)(전화문의 사절(문의폭주로 다른 업무를 할 수가 없습니다 죄송합니다ㅜㅜ) ;   워크넷이나 이메일로 지원하시면 검토후 면접 대상자에게 개별 연락드립니다.)',
    rcptddlnday: '2022.01.12',
    eplymtform: '기간의 정함이 있는 근로계약6 개월/ 파견근로 비희망/ 대체인력채용 비희망',
    rcrtmtnoppl: '15명',
    wagecdn: '일급100;000원 이상;',
    crrcdn: '경력 (최소3년) 우대',
    acbg: '고졸',
    forlangablty: '',
    major: '',
    qlfclcn: '',
    hpmltrysvrcexptnrqrmnt: '비희망',
    prfrnlcdn: '고용허가제',
    etcpfrncs: '',
    slctnmthd: '면접',
    rcptmthd: '방문;이메일',
    sbmsndocsformatch: '',
    sbmsndocsprmtrl: '이력서',
    plcwork:
      '(16910)  경기도 용인시 기흥구 마북로154번길 16; 경기도 용인시 기흥구 마북동 212-2 (마북동; 교동마을정광아파트)',
    ogdpinduscmplx: '',
    nrbysbwystn: '',
    workhrform: '평일 : (오전) 6시 30분~(오후) 5시 00분(휴게시간 포함); 주 6일 근무',
    pnsn4majinsrn: '국민연금 고용보험 산재보험 의료보험',
    svpaygivemthd: '퇴직금',
    etcwlfrbnft: '',
    dsabldcnvntfclts: '',
    deptnm: '',
    telno: '028970939',
    fxno: '02-899-3700',
    addr: '14322 경기도 광명시 하안로 60; B동 601호  (주)주현개발',
  },
  {
    no: 77,
    conm: '에스-드림(S-dream)',
    sj: '앱 · 웹 개발 / 서비스; 컨텐츠 기획 / 마케...',
    qlfcrqrmnt: '경력',
    regymd: '2022-01-07',
    ddlnymd: '2022-01-31',
    dutycn:
      '■ 채용직무 : 앱 · 웹 개발 / 서비스  - 담당업무 : 앱 · 웹 개발회사와 커뮤니케이션 및 서비스 유지 보수  - 자격요건     · 학력무관    · 관련 분야 1년 이상 경력    · 개발과 서비스 기획 / 운영 경험    · 앱 개발회사와 개발과정에서 원활한 커뮤니케이션 가능   - 우대사항    · 관련 학과 전공자    · 관련 자격증 보유자    · 유관업무 경험/  경력자    · 앱 · 웹 개발 / 서비스 기획; 실행; 운영까지의 경험자 ■ 채용직무 : 컨테츠 기획 / 마케팅  - 담당업무 : 컨텐츠 기획과 마케팅 운영 성과분석  - 자격요건      · 학력무관     · 관련 분야 1년 이상 경력     · 체계화된 기획문서 작성 경험     · 원활한 커뮤니케이션 가능  - 우대사항     · 관련 학과 전공자     · 관련 자격증 보유자     · 유관업무 경험 /  경력자     · 행사 대행사 경력자',
    rcptddlnday: '채용시까지',
    eplymtform: '기간의 정함이 없는 근로계약/ 파견근로 비희망/ 대체인력채용 비희망',
    rcrtmtnoppl: '2명',
    wagecdn: '연봉30;000;000원 이상 ~ 36;000;000원 이하; 면접 후 재조정 가능',
    crrcdn: '경력 (최소1년) 우대',
    acbg: '학력무관',
    forlangablty: '',
    major: '',
    qlfclcn: '',
    hpmltrysvrcexptnrqrmnt: '비희망',
    prfrnlcdn: '',
    etcpfrncs: '',
    slctnmthd: '서류;면접',
    rcptmthd: '방문;워크넷',
    sbmsndocsformatch: '',
    sbmsndocsprmtrl: '이력서;자기소개서',
    plcwork: '(16971)  경기도 용인시 기흥구 신구로54번길 5-4; 오복빌딩 1층 102호(에스드림) (구갈동)',
    ogdpinduscmplx: '',
    nrbysbwystn: '에버라인 기흥 6번출구 800M',
    workhrform: '평일 : (오전) 9시 00분~(오후) 6시 00분; 주 5일 근무; 평균근무시간 : 40',
    pnsn4majinsrn: '국민연금 고용보험 산재보험 의료보험',
    svpaygivemthd: '퇴직금',
    etcwlfrbnft: '기타(-자율복장-1개월 만근 시 연차 발생-연말 상여 지급)',
    dsabldcnvntfclts: '',
    deptnm: '',
    telno: '0316935003',
    fxno: '031-693-5003',
    addr: '16971 경기도 용인시 기흥구 신구로54번길 5-4; 오복빌딩 1층 102호(에스드림) (구갈동)',
  },
  {
    no: 414,
    conm: '피앤씨주식회사',
    sj: 'IoT Device의 펌웨어 및 엠베디드 소프트웨...',
    qlfcrqrmnt: '경력',
    regymd: '2022-01-04',
    ddlnymd: '2022-01-20',
    dutycn:
      '펌웨어 및 임베디드 소프트웨어 프로그램 - 수행업무 : 전자회로 설계 검토 및 (유무선통신; 시스템 제어버스등); 센서융합 Art Work;                    Firmware Embeded 시스템개발 - 필수기술 : C/C++ 및 Python 프로그래밍능력; 전자회로 검토 및 측정시험과 디버깅기술  - 우대사항 : 기능시험 및 성능시험 경험자 우대;  전자공학관련 자격보유시 우대',
    rcptddlnday: '2022.01.20',
    eplymtform: '기간의 정함이 없는 근로계약/ 파견근로 비희망/ 대체인력채용 비희망',
    rcrtmtnoppl: '1명',
    wagecdn: '연봉40;000;000원 이상 ~ 45;000;000원 이하; 상여금 : 100(미 포함) ; 면접 후 재조정 가능',
    crrcdn: '경력 (최소5년) 필수',
    acbg: '대졸(2~3년)-대졸(4년)',
    forlangablty: '',
    major: '응용 소프트웨어 공학(학과 : 컴퓨터소프트웨어공학전공)',
    qlfclcn: '',
    hpmltrysvrcexptnrqrmnt: '비희망',
    prfrnlcdn: '',
    etcpfrncs: '근무지는 제주본사이나  또는 경기 용인(수원시에 근접) 가능합니다.',
    slctnmthd: '서류;면접',
    rcptmthd: '워크넷',
    sbmsndocsformatch: '',
    sbmsndocsprmtrl: '이력서;자기소개서;경력증명서',
    plcwork: '(16954)  경기도 용인시 기흥구 흥덕1로 13 (영덕동)',
    ogdpinduscmplx: '',
    nrbysbwystn: '',
    workhrform: '평일 : (오전) 9시 00분~(오후) 6시 00분; 주 5일 근무; 평균근무시간 : 40',
    pnsn4majinsrn: '국민연금 고용보험 산재보험 의료보험',
    svpaygivemthd: '퇴직연금',
    etcwlfrbnft: '',
    dsabldcnvntfclts: '장애인용 승강기;건물 내부 경사로',
    deptnm: '',
    telno: '0647558238',
    fxno: '064-755-8239',
    addr: '63149 제주특별자치도 제주시 동성길 6; 피앤씨(주)',
  },
]
